version: '3.9'

services:
  database:
    image: postgres
    container_name: postgress
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=teste
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
