version: '3'

services:
  app_soujunior:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_soujunior
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db_soujunior 
  db_soujunior:
    container_name: db_soujunior 
    image: postgres:14
    environment:
      POSTGRES_USER: "soujunior"
      POSTGRES_PASSWORD: "soujunior"
      POSTGRES_DB: "soujunior"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
